### ISSUE TITLE
Ability to leak server.js file

### ISSUE THREAD

**Issue by miuirussia** [fenivana/vue-ssr-boilerplate#1]
When builded, you can leak file server.js (passwords, and other leaks possible) with http://localhost:8200/assets/server.js link.

**Comment by jiangfengming** [comment]
`http://localhost:8200/assets/server.js` is compiled from `src/server-entry.js`, it is basically the same as `client.js`, only some tweaks in the entry file to make the browser code could run on server side. So there won't have sensitive data in the file. One thing need to remember is, the codes in `src` folder will be run on both browser and server side, so DO NOT put sensitive data in `src` folder, as well as `runtimeConfig` in confg file.
