### ISSUE TITLE
[help]Running server for ssr

### ISSUE THREAD

**Issue by marcio199226** [fenivana/vue-ssr-boilerplate#2]
Hi i want to try develop an app rendered on server side and i would use your boilerplate to start work on it.

But i have a trouble after cloning your repo and running npm run dev im not able to see server side rendered app on localhost:8200 can you help me?

The app on port 8200 (for ssr) isn't reachable

Ok sorry for stupid question i did not remember about execute node server.js but i'm on node 4.5.x v and i have a lot of errors since which version of node this boilerplate is supported?

nevermind i have upgraded to 7.x version and all works, sorry for stupid issue

**Comment by jiangfengming** [comment]
Sorry I haven't mention the version of node.js in README, just added.
